
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test
  host: localhost
  port: 5432
  username: postgres
  password: postgres

  
test:
  <<: *default
  database: test
  host: localhost
  port: 5432
  username: postgres
  password: postgres


production:
  <<: *default
  database: test
  host: localhost
  port: 5432
  username: postgres
  password: postgres
